language: java

sudo: required
cache: bundler
bundler_args: --without production --deployment

jdk:
  - oraclejdk9

before_install:
  - curl -s api.sdkman.io | bash
  - source /home/travis/.sdkman/bin/sdkman-init.sh # ターミナル上での表示結果
  - sdk list gradle
  - sdk install gradle 4.4.1 # gradle version 4.2.1 以降を使う
  - sdk default gradle 4.4.1

install:
  - curl -O http://www.antlr.org/download/antlr-4.7.1-complete.jar # version4の最新版を導入すること
  - java -cp ./antlr-4.7.1-complete.jar org.antlr.v4.Tool # ツールの確認
  - java -cp ./antlr-4.7.1-complete.jar org.antlr.v4.Tool ./src/main/resources/Classes.g4 # ./src/main/resources ディレクトリ内に構文解析機を生成
  - rm antlr-4.7.1-complete.jar
  - mkdir ./src/main/java/parser/
  - mv ./src/main/resources/Classes*.java ./src/main/resources/*.tokens ./src/main/java/parser/.
  - rm ./src/main/resources/*.interp
  - du -a ./
