language: java

sudo: required

jdk:
  - oraclejdk9

before_install:
  - curl -s api.sdkman.io | bash
  - source /home/travis/.sdkman/bin/sdkman-init.sh # ターミナル上での表示結果
  - sdk list gradle
  - sdk install gradle 4.2.1
  - sdk default gradle 4.2.1
  - ls -al

install:
  - echo install!

after_install:
  - echo after_install!!

before_script:
  - echo before_script!!!

script:
  - sudo chmod +x gradlew
  - gradle clean build