language: java

sudo: required

jdk:
  - oraclejdk9

before_install:
  - curl -s api.sdkman.io | bash
  - source .sdkman/bin/sdkman-init.sh
  - sdk list gradle
  - sdk install gradle 4.2.1
  - sdk default gradle 4.2.1

script:
  - sudo chmod +x gradlew
  - gradle clean build