language: java

sudo: required
cache: bundler
bundler_args: --without production --deployment

jdk:
  - oraclejdk9

before_install:
  - curl -s api.sdkman.io | bash
  - source /home/travis/.sdkman/bin/sdkman-init.sh # ターミナル上での表示結果
  - sdk list gradle
  - sdk install gradle 4.4.1 # gradle version 4.2.1 以降を使う
  - sdk default gradle 4.4.1

install:
  - curl -O http://www.antlr.org/download/antlr-4.7.1-complete.jar # version4の最新版を導入すること
  - java -cp ./antlr-4.7.1-complete.jar org.antlr.v4.Tool # ツールの確認
  - java -cp ./antlr-4.7.1-complete.jar org.antlr.v4.Tool ./src/main/resources/Classes.g4 # ./src/main/resources ディレクトリ内に構文解析機を生成
  - rm antlr-4.7.1-complete.jar
  - mkdir ./src/main/java/parser/
  - mv ./src/main/resources/Classes*.java ./src/main/resources/*.tokens ./src/main/java/parser/.
  - rm ./src/main/resources/*.interp
  - du -a ./

after_success:
  - pwd
  # - gradle test jacocoTestReport coveralls -repotoken $COVERALL_TOKEN
  - COVERALLS_REPO_TOKEN=$COVERALL_TOKEN gradle coveralls


env:
  global:
    secure: "AMxrZCJpVZ5FG2T/y63Gfs4gmhgVbs8PYxF/qVMhOga0BHvsA1QIn+WDgwZT1KGHuNoA9GYg6zEXVGlk3jEzQlO5o1+P5BlSQ+kYzWXG1eg0QtgeW+q33vi2LfEOJ3KP5Bbe1BDSxMPZ7WixKYP82P9F8g6f+O+4P2qbBEmSFRqSvOLLg5KEJW9+P2ewOtk9HghIYCL+VlZusPriX3MCUIk5qVL4OcBHqXA3sLrpP2hk6eVWNVFp5WbTjoMnWG7zmuALmfU2xdNg8yAFZqtLm1nW3xhAsh0NNM/LY0ZvarH2tbWcxi1MaXDYNI867MM/9K2u1UutHAgy2oluqjCYs+9Gteg9/pZfpSQjBd0p1qQ1utBKCaqZyaCe9FLVkuRBZirwZft+mkTAqUWIbTf5DYrAWr70DNxFrjaPGYzQO+b5IE+FhpprlFNdUc7z1+1FW69rxg9TaAogzxZk4ERVlZAeVh8zW8ZFT6s3EzFc67SZ4eukBO3b/DvVHLrw03y55slZkkMf9Tzg6EZO1zJTTtCrt4/tUZJdf6RFPCSLN1P7FSq0C+KfH/YaqnhL+T3RbVw6O+96nIBe60xNa6eOAyQVsyhZkV81YSV1YObYp2pAPv8Win6rxERHGYjFLknkQ/M9Hri4kFBC/fnfK4KOsuRJb0lRNYLjEqiSag2onXk="
